//
//  TermsOfServiceView.swift
//  OwlSeerLite
//
//  Terms of Service - Industry Best Practices
//

import SwiftUI

struct TermsOfServiceView: View {
    @Environment(\.dismiss) private var dismiss
    
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {
                // Header
                VStack(alignment: .leading, spacing: 8) {
                    Text("Terms of Service")
                        .font(.largeTitle.bold())
                    
                    Text("Last Updated: February 2025")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }
                
                // Acceptance
                sectionView(title: "1. Acceptance of Terms") {
                    Text("""
                    By downloading, installing, or using OwlSeer Lite ("the App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the App.

                    We reserve the right to modify these Terms at any time. Your continued use of the App following any changes constitutes your acceptance of the new Terms.
                    """)
                }
                
                // Service Description
                sectionView(title: "2. Service Description") {
                    Text("""
                    OwlSeer Lite is an AI-powered content creation assistant designed to help TikTok creators with:

                    • Generating engaging video hooks and scripts
                    • Providing content ideas and trend analysis
                    • Formatting scripts for video production
                    • Optional web search for real-time information

                    The App offers both a free tier with limited daily usage and the option to use your own API keys for extended functionality.
                    """)
                }
                
                // User Responsibilities
                sectionView(title: "3. User Responsibilities") {
                    Text("""
                    By using the App, you agree to:

                    • **Comply with Laws**: Use the App in compliance with all applicable laws and regulations
                    • **Appropriate Use**: Not use the App to generate harmful, illegal, defamatory, or inappropriate content
                    • **Platform Guidelines**: Ensure any content created with the App complies with TikTok and other platforms' community guidelines
                    • **Account Security**: Keep your API keys secure and not share them with others
                    • **Accurate Information**: Provide accurate information when required
                    • **Age Requirement**: Be at least 13 years old to use the App
                    """)
                }
                
                // AI-Generated Content
                sectionView(title: "4. AI-Generated Content Disclaimer") {
                    VStack(alignment: .leading, spacing: 12) {
                        Text("""
                        **Important**: All content generated by the AI is provided for reference and inspiration purposes only.
                        """)
                        .fontWeight(.semibold)
                        
                        Text("""
                        • **No Guarantees**: We do not guarantee the accuracy, completeness, or suitability of AI-generated content
                        • **User Responsibility**: You are solely responsible for reviewing, editing, and verifying any content before use
                        • **No Professional Advice**: AI-generated content does not constitute professional, legal, financial, or medical advice
                        • **Potential Similarities**: Generated content may inadvertently resemble existing works; users must verify originality
                        • **Platform Compliance**: Users must ensure generated content complies with platform-specific rules and guidelines
                        """)
                    }
                }
                
                // Intellectual Property
                sectionView(title: "5. Intellectual Property") {
                    Text("""
                    **App Ownership**: The App, including its design, features, and code, is owned by OwlSeer and protected by intellectual property laws.

                    **User Content**: You retain ownership of any original content you create using the App. However, you grant us a limited license to use anonymized, aggregated feedback to improve our services.

                    **AI Output**: Content generated by AI is provided for your use, but we make no claims regarding the intellectual property status of AI-generated content. Users are responsible for ensuring they have appropriate rights to use any generated content.

                    **Third-Party Rights**: You agree not to use the App to infringe on the intellectual property rights of others.
                    """)
                }
                
                // Limitation of Liability
                sectionView(title: "6. Limitation of Liability") {
                    Text("""
                    TO THE MAXIMUM EXTENT PERMITTED BY LAW:

                    • The App is provided "AS IS" and "AS AVAILABLE" without warranties of any kind
                    • We disclaim all warranties, express or implied, including merchantability, fitness for a particular purpose, and non-infringement
                    • We are not liable for any indirect, incidental, special, consequential, or punitive damages
                    • Our total liability shall not exceed the amount you paid for the App (if any)
                    • We are not responsible for any losses resulting from AI-generated content, including but not limited to reputational damage, lost opportunities, or platform violations
                    """)
                }
                
                // Third-Party Services
                sectionView(title: "7. Third-Party Services") {
                    Text("""
                    The App integrates with third-party AI and search services:

                    • **AI Providers**: Moonshot AI, OpenAI, Anthropic, Google
                    • **Search Providers**: Tavily, SerpAPI (optional)

                    Your use of these services is subject to their respective terms of service and privacy policies. We are not responsible for the performance, availability, or content provided by third-party services.

                    If you use custom API keys, you are responsible for compliance with the respective provider's terms of service and usage policies.
                    """)
                }
                
                // Free Tier and Usage Limits
                sectionView(title: "8. Free Tier and Usage Limits") {
                    Text("""
                    • Free tier users receive a limited number of messages per day
                    • Usage limits reset daily at midnight (local time)
                    • We reserve the right to modify free tier limits at any time
                    • Abuse of the free tier may result in temporary or permanent restrictions
                    • Users may bypass free tier limits by configuring their own API keys
                    """)
                }
                
                // Termination
                sectionView(title: "9. Termination") {
                    Text("""
                    • You may stop using the App at any time by uninstalling it
                    • We may terminate or suspend your access to the App at any time, without notice, for conduct that we believe violates these Terms or is harmful to other users or the App
                    • Upon termination, all locally stored data remains on your device unless you delete the App
                    """)
                }
                
                // Governing Law
                sectionView(title: "10. Governing Law") {
                    Text("""
                    These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which the App developer is established, without regard to conflict of law principles.

                    Any disputes arising from these Terms or your use of the App shall be resolved through binding arbitration or in the courts of the applicable jurisdiction.
                    """)
                }
                
                // Severability
                sectionView(title: "11. Severability") {
                    Text("""
                    If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.
                    """)
                }
                
                // Contact
                sectionView(title: "12. Contact Information") {
                    Text("""
                    For questions about these Terms of Service, please contact us:

                    • Email: tech@owlseer.com
                    • In-App: Settings > Feedback

                    We will respond to inquiries within a reasonable timeframe.
                    """)
                }
                
                Spacer(minLength: 40)
            }
            .padding()
        }
        .navigationTitle("Terms of Service")
        .navigationBarTitleDisplayMode(.inline)
    }
    
    // MARK: - Helper Views
    
    private func sectionView<Content: View>(title: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            Text(title)
                .font(.title2.bold())
            
            content()
                .font(.body)
                .foregroundStyle(.primary)
        }
    }
}

#Preview {
    NavigationStack {
        TermsOfServiceView()
    }
}
